// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUTWocUajigcLwesQY5VAOz0DnThzlI7s',
    appId: '1:654846409027:web:7d4125ed24b4d01e8917f6',
    messagingSenderId: '654846409027',
    projectId: 'reddit-clone-4b6a9',
    authDomain: 'reddit-clone-4b6a9.firebaseapp.com',
    storageBucket: 'reddit-clone-4b6a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqztE5wKhx9c5Sv9oYCdQ6pJPoH_HX8n0',
    appId: '1:654846409027:android:a1614e8ab7aa46898917f6',
    messagingSenderId: '654846409027',
    projectId: 'reddit-clone-4b6a9',
    storageBucket: 'reddit-clone-4b6a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBNhOKDRtLVvhfmyuhG_X5eQ0JVF6HJTE',
    appId: '1:654846409027:ios:7c1d1061e23360c98917f6',
    messagingSenderId: '654846409027',
    projectId: 'reddit-clone-4b6a9',
    storageBucket: 'reddit-clone-4b6a9.appspot.com',
    iosClientId: '654846409027-kplc92duo7ko4rtka9fb0bkt9mnia7o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBNhOKDRtLVvhfmyuhG_X5eQ0JVF6HJTE',
    appId: '1:654846409027:ios:6e93aa2de03bf90d8917f6',
    messagingSenderId: '654846409027',
    projectId: 'reddit-clone-4b6a9',
    storageBucket: 'reddit-clone-4b6a9.appspot.com',
    iosClientId: '654846409027-cqq9m35h4euol9r03hk7qm9eq5d6132a.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit.RunnerTests',
  );
}
